# Generated by Django 4.2.2 on 2023-06-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classviewex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskList',
            new_name='Task',
        ),
    ]
