# Generated by Django 4.2.2 on 2023-06-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='BasicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=80, verbose_name='Last Name')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('designation', models.CharField(max_length=80, verbose_name='Designation')),
                ('address', models.TextField(max_length=200, verbose_name='Address')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=90)),
                ('relationship_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=90)),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('zipcode', models.IntegerField(verbose_name='Zip Code')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.allstate')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='TechLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechLanguageName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KnownTechLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techLangExpertise', models.CharField(max_length=90)),
                ('techLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.techlanguages')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.basicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='KnownLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.language')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.basicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=90, verbose_name='Company Name')),
                ('ex_designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('from_date', models.DateField(verbose_name='From')),
                ('to_date', models.DateField(verbose_name='To')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.basicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardname', models.CharField(max_length=90, verbose_name='Name of board')),
                ('passingyear', models.DateField(verbose_name='Passing Year')),
                ('percentage', models.IntegerField(verbose_name='Percentages')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.basicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=90)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.allstate')),
            ],
        ),
    ]
