# Generated by Django 4.2.2 on 2023-06-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='referenceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=100, verbose_name='Name')),
                ('ref_contact', models.IntegerField(verbose_name='Contact')),
                ('ref_relation', models.CharField(max_length=100, verbose_name='Relation')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.basicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='preferenceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_loaction', models.CharField(choices=[('ahmedabad', 'Ahmedabad'), ('palanpur', 'Palanpur'), ('surat', 'Surat'), ('rajkot', 'Rajkot')], max_length=255, verbose_name='Location')),
                ('notice_period', models.IntegerField(verbose_name='Notice Period')),
                ('expected_ctc', models.CharField(max_length=255, verbose_name='Expected CTC')),
                ('current_ctc', models.CharField(max_length=255, verbose_name='Current CTC')),
                ('pref_department', models.CharField(choices=[('marketing', 'Marketing'), ('management', 'Management'), ('devlopment', 'Devlopment'), ('design', 'Design')], max_length=255, verbose_name='Department')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobForm.basicdetail')),
            ],
        ),
    ]
