# Generated by Django 4.2.2 on 2023-06-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobForm', '0002_referencedetail_preferencedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationdetail',
            old_name='boardname',
            new_name='board_name',
        ),
        migrations.RenameField(
            model_name='educationdetail',
            old_name='passingyear',
            new_name='passing_year',
        ),
    ]
