# Generated by Django 4.2.2 on 2023-06-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobForm', '0003_rename_boardname_educationdetail_board_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='passing_year',
            field=models.IntegerField(verbose_name='Passing Year'),
        ),
    ]
